(()=>{
'use strict';
const C=DelveCore,$=id=>document.getElementById(id),SAVE='windplay:ascii-delve:v1',RECORD='windplay:ascii-delve:record:v1';let state,saveError=false,record={wins:0,deepest:1},credited=false;
try{state=C.restore(localStorage.getItem(SAVE));const r=JSON.parse(localStorage.getItem(RECORD));if(r&&Number.isInteger(r.wins)&&r.wins>=0&&Number.isInteger(r.deepest)&&r.deepest>=1&&r.deepest<=5)record=r;}catch(_){saveError=true;}
state=state||C.newGame();credited=state.status==='won';const renderer=new DelveRenderer($('dungeon'));
const mapButton=document.createElement('button');mapButton.id='map-toggle';mapButton.textContent='地图 M';mapButton.setAttribute('aria-pressed','false');mapButton.style.cssText='font-size:12px;min-height:36px;padding:4px 9px';document.querySelector('.map-bar').append(mapButton);mapButton.onclick=()=>{renderer.full=!renderer.full;mapButton.setAttribute('aria-pressed',String(renderer.full));mapButton.textContent=renderer.full?'视野 M':'地图 M';renderer.draw();};
function save(){record.deepest=Math.max(record.deepest,state.floor);if(state.status==='won'&&!credited){record.wins++;credited=true;}try{localStorage.setItem(SAVE,C.serialize(state));localStorage.setItem(RECORD,JSON.stringify(record));saveError=false;}catch(_){saveError=true;}$('save-status').textContent=saveError?'保存不可用 · 本次仍可完整游玩':'已自动保存 · 可随时回来';}
function update(){renderer.set(state);const p=state.player;$('floor-number').innerHTML='B'+state.floor+'<span> / B5</span>';$('floor-title').textContent=C.FLOOR_NAMES[state.floor-1];$('turn').textContent='回合 '+String(state.turn).padStart(4,'0');$('role-name').textContent=C.ROLES[state.role].name;$('player-level').textContent='LV. '+String(p.level).padStart(2,'0');$('hp').textContent=p.hp+' / '+p.maxHp;$('mobile-hp').textContent=p.hp+' / '+p.maxHp;$('mobile-hp-fill').style.transform='scaleX('+p.hp/p.maxHp+')';$('mobile-hp-fill').style.background=p.hp<p.maxHp*.3?'var(--danger)':'var(--green)';$('hp-fill').style.transform='scaleX('+p.hp/p.maxHp+')';$('hp-fill').style.background=p.hp<p.maxHp*.3?'var(--danger)':'var(--green)';$('hp-bar').setAttribute('aria-valuemax',p.maxHp);$('hp-bar').setAttribute('aria-valuenow',p.hp);for(const id of ['attack','defense'])$(id).textContent=p[id];$('gold').textContent=state.gold;$('xp').textContent='经验 '+p.xp+' / '+p.level*18;$('weapon').textContent=p.weapon;$('armor').textContent=p.armor;$('key').textContent=p.key?'铜钥匙 · 已找到':'尚未找到';$('potion-count').textContent=p.potions;$('charge-count').textContent=p.charges;
 $('objective').textContent=p.key?(state.floor===5?'击败守火者 W，抵达阶梯取回火种':'找到阶梯 >，按 E 继续下潜'):'寻找铜钥匙 k，再走向阶梯 >';const floors=state.tiles.filter(t=>t!=='#').length,explored=state.seen.filter((seen,i)=>seen&&state.tiles[i]!=='#').length;$('explored').textContent='探索 '+Math.round(explored/floors*100)+'%';
 $('log').replaceChildren();state.log.slice(0,10).forEach(text=>{const li=document.createElement('li');li.textContent=text;$('log').append(li);});$('live-status').textContent=state.log[0]+' 生命 '+p.hp+'，位置 '+p.x+'，'+p.y+'。';$('shop').hidden=state.shop!=='open';$('seed-label').textContent='SEED / '+state.seedText;$('record').textContent='最深 B'+record.deepest+' · '+record.wins+' 次带回火种';
 document.querySelectorAll('[data-action],[data-move]').forEach(b=>b.disabled=state.status!=='playing');$('heal').disabled=state.status!=='playing'||p.potions===0||p.hp===p.maxHp;$('pulse').disabled=state.status!=='playing'||p.charges===0;
 $('run-ending').hidden=state.status==='playing';if(state.status!=='playing'){const won=state.status==='won';$('ending-symbol').textContent=won?'*':'@';$('ending-title').textContent=won?'天，终于亮了。':'灯火暂时熄灭。';$('ending-summary').textContent=(won?'你带回了不灭的火种。':'每一次倒下，都让下一段旅程更清晰。')+' 抵达 B'+state.floor+' · '+state.turn+' 回合 · 击败 '+state.kills+' 位敌人 · 发现 '+state.relics+' 处遗迹。';}
}
function act(action){if(!$('new-run').hidden||!$('help').hidden)return;C.step(state,action);save();update();}
document.querySelectorAll('[data-move]').forEach(button=>button.onclick=()=>{const [dx,dy]=button.dataset.move.split(',').map(Number);act({type:'move',dx,dy});});document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>act({type:button.dataset.action}));document.querySelectorAll('[data-buy]').forEach(button=>button.onclick=()=>act({type:'buy',item:button.dataset.buy}));
function newPanel(open){$('new-run').hidden=!open;$('new-toggle').setAttribute('aria-expanded',String(open));if(open){$('seed').value=state.seedText;$('role').value=state.role;$('new-run').scrollIntoView({block:'nearest'});$('role').focus();}else $('new-toggle').focus();}
$('new-toggle').onclick=()=>newPanel($('new-run').hidden);$('cancel-run').onclick=()=>newPanel(false);$('ending-new').onclick=()=>newPanel(true);$('random-seed').onclick=()=>{$('seed').value='EMBER-'+Math.random().toString(36).slice(2,8).toUpperCase();};
function start(seed,role){state=C.newGame(seed.trim()||'LANTERN',role);credited=false;renderer.full=false;mapButton.setAttribute('aria-pressed','false');mapButton.textContent='地图 M';$('new-run').hidden=true;$('new-toggle').setAttribute('aria-expanded','false');save();update();$('dungeon').focus();}
$('start-run').onclick=()=>start($('seed').value,$('role').value);$('try-again').onclick=()=>start(state.seedText,state.role);
function help(open){$('help').hidden=!open;$('help-toggle').setAttribute('aria-expanded',String(open));if(open){$('help').scrollIntoView({block:'nearest'});$('help-close').focus();}else $('help-toggle').focus();}
$('help-toggle').onclick=()=>help($('help').hidden);$('help-close').onclick=()=>help(false);
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase();if(k==='escape'){if(!$('help').hidden)help(false);if(!$('new-run').hidden)newPanel(false);return;}if(e.target.tagName==='BUTTON'&&(k===' '||k==='enter'))return;const dirs={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(dirs[k]){e.preventDefault();if(e.repeat)return;const [dx,dy]=dirs[k];act({type:'move',dx,dy});}else if(['h','f','e','.',' ','m'].includes(k)){e.preventDefault();if(e.repeat)return;if(k==='m')mapButton.click();else act({type:{h:'heal',f:'pulse',e:'interact','.':'wait',' ':'wait'}[k]});}});
let touchStart=null;$('dungeon').addEventListener('pointerdown',e=>{touchStart={x:e.clientX,y:e.clientY};$('dungeon').setPointerCapture(e.pointerId);});$('dungeon').addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.hypot(dx,dy)>18)act({type:'move',dx:Math.abs(dx)>Math.abs(dy)?Math.sign(dx):0,dy:Math.abs(dy)>=Math.abs(dx)?Math.sign(dy):0});});$('dungeon').addEventListener('pointercancel',()=>touchStart=null);
document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});save();update();
})();
