(()=>{
'use strict';
const C=PrismCore,$=id=>document.getElementById(id),key='windplay:prism-path:v1';let progress=C.restoreProgress(null),canSave=true;
try{progress=C.restoreProgress(localStorage.getItem(key));}catch(_){canSave=false;}
let state=C.create(progress.selected),history=[],hints=0,walking=false,walkToken=0;const renderer=new PrismRenderer($('scene'));const par=C.levels.map(l=>C.solve(C.create(l.id)).length);
function save(){try{localStorage.setItem(key,JSON.stringify({version:1,...progress}));}catch(_){canSave=false;}$('save-note').textContent=canSave?'旅程会自动保存在此浏览器':'浏览器未允许保存；本次仍可完整游玩';}
function chapterList(){const list=$('level-list');list.replaceChildren();C.levels.forEach(l=>{const b=document.createElement('button');b.innerHTML='<span>'+String(l.id+1).padStart(2,'0')+'</span>'+l.name+'<small>'+(progress.completed[l.id]?'✓':'')+'</small>';b.setAttribute('aria-current',String(l.id===state.level));b.setAttribute('aria-label','第 '+(l.id+1)+' 章 '+l.name+(progress.completed[l.id]?'，已完成':''));b.addEventListener('click',()=>load(l.id));list.append(b);});$('progress').textContent=Object.keys(progress.completed).length+' / 10 章已完成';}
function announce(text){$('status').textContent=text;}
function update(animate=false){const l=C.levels[state.level];renderer.set(state,animate);$('chapter-number').textContent=String(l.id+1).padStart(2,'0');$('level-name').textContent=l.name;$('story').textContent=l.story;$('objective').textContent=l.help;$('world-label').textContent='第 '+(l.id+1)+' 章 · '+l.name;$('view-label').textContent=['东南视角','西南视角','西北视角','东北视角'][state.view];$('lights').textContent=state.lights.toString(2).replaceAll('0','').length+' / '+l.allLights.toString(2).replaceAll('0','').length;$('moves').textContent=state.moves;
 $('rotate-left').disabled=$('rotate-right').disabled=!C.canRotate(state)||state.won||walking;$('undo').disabled=!history.length||walking;$('switch').hidden=l.nodes[state.node].kind!=='switch';$('switch').disabled=state.won||walking;
 $('rotation-rule').textContent=l.restricted?(C.canRotate(state)?'已站在星盘上 · 可以旋转':'走到圆环星盘，再转动世界'):'转动世界，让断桥相遇';[...$('compass').children].forEach((n,i)=>n.classList.toggle('active',i===state.view));
 $('paths').replaceChildren();C.available(state).forEach((node,i)=>{const b=document.createElement('button');const n=l.nodes[node],name=n.kind==='goal'?'拱门':n.kind==='light'&&!(state.lights&n.bit)?'星光':n.kind==='switch'?'机关':n.dial?'星盘':'石台';b.textContent=(i+1)+' · '+name+' '+(node+1);b.disabled=state.won||walking;b.onclick=()=>act({type:'move',node});$('paths').append(b);});
 $('completion').hidden=!state.won;if(state.won){const stars=progress.completed[state.level]?.stars||1;$('complete-title').textContent=state.level===9?'所有光，都已归来。':'光，找到归途。';$('complete-detail').textContent='本章 '+state.moves+' 步 · '+stars+' / 3 星\n'+(hints?'你跟随指引完成了旅程。':'再试一次，寻找更短的路。');$('next').textContent=state.level===9?'回到第一章 →':'进入下一章 →';}
}
function act(action,fromWalk=false){if(walking&&!fromWalk)return;const next=C.apply(state,action);if(next===state){if(action.type==='rotate')announce('先走到带圆环的星盘，才能旋转。');return;}history.push(state);state=next;
 if(state.won){const stars=1+Number(state.moves<=par[state.level]*1.35)+Number(hints===0),old=progress.completed[state.level];progress.completed[state.level]={moves:Math.min(old?.moves||Infinity,state.moves),stars:Math.max(old?.stars||0,stars)};save();chapterList();announce('第 '+(state.level+1)+' 章完成。');}
 else if(action.type==='switch')announce('机关已'+((state.switches&C.levels[state.level].nodes[state.node].bit)?'开启':'关闭')+'。');
 else if(state.node===C.levels[state.level].goal)announce('拱门还在等待。请先收齐所有星光。');
 else announce(action.type==='rotate'?'视角已切换，寻找相接的金色桥头。':'旅人来到石台 '+(state.node+1)+'。');update(action.type==='rotate');}
function load(id){walkToken++;walking=false;state=C.create(id);history=[];hints=0;progress.selected=id;save();chapterList();announce(C.levels[id].restricted?'带圆环的石台是星盘，站在这里才能转动世界。':'点击石台移动。试着转动世界，接上金色桥头。');update();}
$('rotate-left').onclick=()=>act({type:'rotate',direction:-1});$('rotate-right').onclick=()=>act({type:'rotate',direction:1});$('switch').onclick=()=>act({type:'switch'});$('restart').onclick=()=>load(state.level);$('next').onclick=()=>load((state.level+1)%10);
$('undo').onclick=()=>{if(!history.length||walking)return;state=history.pop();announce('已撤回一步。');update(true);};
$('hint').onclick=()=>{if(state.won)return;const plan=C.solve(state);hints++;const a=plan?.[0];announce(!a?'已经抵达终点。':a.type==='move'?'下一步：走到石台 '+(a.node+1)+'，可用下方路径按钮。':a.type==='rotate'?'下一步：向'+(a.direction===1?'右':'左')+'旋转一次。':'下一步：切换脚下的机关。');};
$('scene').onclick=async e=>{if(walking||state.won)return;const rect=e.currentTarget.getBoundingClientRect(),target=renderer.hit(e.clientX-rect.left,e.clientY-rect.top);if(target===undefined)return;const route=C.route(state,target);if(!route){announce('这条路还没有连接。试试旋转视角，或寻找机关。');return;}const token=++walkToken;walking=true;update();for(const node of route){if(token!==walkToken)break;act({type:'move',node},true);if(!renderer.reduced.matches)await new Promise(resolve=>setTimeout(resolve,150));}if(token===walkToken){walking=false;update();}};
function help(open){$('help').hidden=!open;$('help-toggle').setAttribute('aria-expanded',String(open));if(open){$('help').scrollIntoView({block:'nearest',behavior:renderer.reduced.matches?'instant':'smooth'});$('help-close').focus();}else $('help-toggle').focus();}
$('help-toggle').onclick=()=>help($('help').hidden);$('help-close').onclick=()=>help(false);
document.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea')||e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase();if(k==='escape'&&!$('help').hidden){help(false);return;}if(e.target.tagName==='BUTTON'&&(k===' '||k==='enter'))return;if(!['q','e','z','r',' ','1','2','3','4','5','6','7','8','9'].includes(k))return;e.preventDefault();if(e.repeat)return;if(k==='q'||k==='e')act({type:'rotate',direction:k==='q'?-1:1});else if(k===' ')act({type:'switch'});else if(k==='z')$('undo').click();else if(k==='r')$('restart').click();else{const n=C.available(state)[Number(k)-1];if(n!==undefined)act({type:'move',node:n});}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(renderer.frame);renderer.angle=state.view*Math.PI/2;}else renderer.draw();});load(progress.selected);
})();
