const test=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/engine.js'),{levels}=require('../src/levels.js');
const tick=(s,input,n=120)=>{for(let i=0;i<n;i++)E.step(s,{...input,jumpPressed:input.jumpPressed&&i===0});};
test('32 independently authored stages in NES order, unique terrain, valid coordinates',()=>{
 assert.equal(levels.length,32);assert.equal(new Set(levels.map(l=>JSON.stringify([l.length,l.pits,l.pipes,l.blocks]))).size,32);
 for(let i=0;i<32;i++){const l=levels[i];assert.equal(l.id,`${1+(i>>2)}-${i%4+1}`);assert.equal(l.stage===4,l.theme==='castle');assert.ok(l.length>100);for(const [x,w] of l.pits)assert.ok(x>=12&&w>0&&x+w<l.length-8);const s=E.create(i);assert.ok(s.solids.length>0);assert.equal(s.status,'playing');assert.ok(s.goal>s.player.x);}
 assert.equal(levels[5].theme,'water');assert.equal(levels[25].theme,'water');assert.equal(levels[28].length,376);
});
test('standing collision is stable and horizontal motion respects pipe walls',()=>{const s=E.create();s.enemies=[];tick(s,{},240);assert.equal(s.player.y+s.player.h,E.GROUND);tick(s,{right:true},500);assert.ok(s.player.x+s.player.w<=28*32);assert.equal(s.status,'playing');});
test('held jump has more height than released jump; landing and jump edge work',()=>{const a=E.create(),b=E.create();tick(a,{jump:true,jumpPressed:true},30);tick(b,{jump:false,jumpPressed:true},30);assert.ok(a.player.y<b.player.y-20);tick(a,{},240);assert.equal(a.player.grounded,true);});
test('question block gives one powerup and grown Mario breaks bricks',()=>{const s=E.create();s.player.x=16*32+4;s.player.y=300;tick(s,{jump:true,jumpPressed:true},30);const b=s.solids.find(b=>b.type==='question'&&b.x===16*32);assert.equal(b.used,true);assert.equal(s.items.filter(i=>i.kind==='mushroom').length,1);E.power(s,1);const brick=s.solids.find(b=>b.type==='brick'&&b.y===256);s.player.x=brick.x+3;s.player.y=brick.y+brick.h+12;s.player.vy=-200;E.step(s,{},.016);tick(s,{jump:true},20);assert.equal(brick.removed,true);});
test('damage downgrades power, grants invulnerability then consumes a life',()=>{const s=E.create();E.power(s,2);E.hit(s);assert.equal(s.player.power,0);assert.equal(s.lives,3);E.hit(s);assert.equal(s.lives,3);s.player.invincible=0;E.hit(s);assert.equal(s.lives,2);assert.equal(s.status,'dead');assert.equal(E.retry(s).lives,2);});
test('pits and timer kill; pauses and results do not simulate',()=>{const a=E.create();a.player.x=70*32;a.player.y=480;tick(a,{},30);assert.equal(a.status,'dead');const b=E.create();b.time=.001;E.step(b);assert.equal(b.status,'dead');const c=E.create();c.status='paused';tick(c,{right:true});assert.equal(c.player.x,80);});
test('stomping koopas produces kickable shells; fire flower shoots',()=>{const s=E.create();const e=s.enemies.find(e=>e.type==='koopa');s.player.x=e.x;s.player.y=e.y-31;s.player.vy=200;tick(s,{},3);assert.equal(e.type,'shell');assert.ok(s.player.vy<0);E.power(s,2);E.step(s,{firePressed:true});assert.equal(s.shots.filter(x=>!x.enemy).length,1);});
test('water jump swims and moving platforms carry riders',()=>{const s=E.create(5);s.player.y=200;E.step(s,{jump:true,jumpPressed:true});assert.ok(s.player.vy<0);const a=E.create(2),b=a.solids.find(b=>b.type==='moving');a.solids=a.solids.filter(x=>x===b||x.type==='ground');a.enemies=[];a.player.x=b.x+5;a.player.y=b.y-a.player.h;a.player.vy=0;tick(a,{},8);assert.ok(Math.abs(a.player.y+a.player.h-b.y)<2);});
test('pipe room returns to original stage without awarding a level clear',()=>{const s=E.create(),b=s.solids.find(b=>b.type==='pipe');s.player.x=b.x+20;s.player.y=b.y-s.player.h;E.step(s,{down:true});assert.ok(s.bonus);assert.equal(s.goal,Infinity);s.player.x=25*32;s.player.y=300;E.step(s,{down:true});assert.equal(s.bonus,null);assert.equal(s.status,'playing');assert.ok(s.player.x>b.x);});
test('all 32 goal transitions and power carryover, final rescue',()=>{for(let i=0;i<32;i++){const s=E.create(i);E.power(s,2);s.player.x=s.goal;s.player.y=100;E.step(s);assert.equal(s.status,i===31?'won':'clear');if(i<31){const n=E.next(s);assert.equal(n.index,i+1);assert.equal(n.player.power,2);assert.equal(n.score,s.score);}}});
test('save restores valid progress and safely rejects corrupted input',()=>{const s=E.create(12);s.score=1400;E.power(s,2);const r=E.restore(E.serialize(s));assert.equal(r.index,12);assert.equal(r.score,1400);assert.equal(r.player.power,2);assert.equal(E.restore('{'),null);assert.equal(E.restore('{"version":1,"index":100}'),null);E.clear(s);assert.equal(E.restore(E.serialize(s)).index,13);});
