(function(root){
 'use strict';const C=root.StrikeCore,$=id=>document.getElementById(id),canvas=$('scene'),isTouch=matchMedia('(pointer:coarse)').matches;
 const BEST='windplay.strike-arena.best.v1',SETTINGS='windplay.strike-arena.settings.v1';
 let state=C.createState(),renderer,playing=false,paused=true,menu='welcome',difficulty='recruit',keys=Object.create(null),shooting=false,aiming=false,look=null,pointerFallback=false,last=0,hudClock=0,mapClock=0,footClock=0,hitTimer=0,killTimer=0,toastTimer=0,audioContext=null,best=null,resultSaved=false,settings={sensitivity:1,fov:78,quality:'high',sound:true},feed=[];
 function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2300);}
 function storageGet(key){try{return localStorage.getItem(key);}catch{return null;}}
 function storagePut(key,value){try{localStorage.setItem(key,value);return true;}catch{return false;}}
 function saveSettings(){storagePut(SETTINGS,JSON.stringify(settings));}
 try{const value=storageGet(BEST);if(value)best=C.parseStats(value);}catch{}
 try{const data=JSON.parse(storageGet(SETTINGS));if(data){settings.sensitivity=C.clamp(Number(data.sensitivity)||1,.4,2.4);settings.fov=C.clamp(Number(data.fov)||78,68,100);settings.quality=data.quality==='low'?'low':'high';settings.sound=data.sound!==false;}}catch{}
 function updateBest(){ $('best-text').textContent=best?`最佳行动：${best.score} 分 / ${best.kills} 击杀 / ${best.headshots} 头部命中`:'第一次行动，等待你的战绩。';}
 function audio(type){
  if(!settings.sound)return;try{
   audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();audioContext.resume();const now=audioContext.currentTime,g=audioContext.createGain();g.connect(audioContext.destination);
   if(type==='rifle'||type==='pistol'||type==='enemy'||type==='explosion'||type==='step'){
    const length=type==='explosion'?.55:type==='step'?.065:.15,buffer=audioContext.createBuffer(1,Math.ceil(audioContext.sampleRate*length),audioContext.sampleRate),data=buffer.getChannelData(0);
    for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,type==='explosion'?2:5);
    const source=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter();source.buffer=buffer;filter.type=type==='step'||type==='explosion'?'lowpass':'bandpass';filter.frequency.value=type==='step'?190:type==='explosion'?600:type==='enemy'?950:1600;filter.Q.value=.8;g.gain.value=type==='enemy'?.055:type==='step'?.1:type==='explosion'?.24:.17;source.connect(filter);filter.connect(g);source.start(now);
    if(type==='rifle'||type==='pistol'){const o=audioContext.createOscillator(),gg=audioContext.createGain();o.frequency.setValueAtTime(type==='rifle'?150:210,now);o.frequency.exponentialRampToValueAtTime(40,now+.11);gg.gain.setValueAtTime(.2,now);gg.gain.exponentialRampToValueAtTime(.001,now+.14);o.connect(gg);gg.connect(audioContext.destination);o.start(now);o.stop(now+.14);}
   }else{const o=audioContext.createOscillator();o.type=type==='hit'?'triangle':'sine';o.frequency.setValueAtTime(type==='kill'?700:type==='reload'?310:type==='hit'?450:130,now);o.frequency.exponentialRampToValueAtTime(type==='kill'?1000:70,now+.1);g.gain.setValueAtTime(.07,now);g.gain.exponentialRampToValueAtTime(.001,now+.12);o.connect(g);o.start(now);o.stop(now+.13);}
  }catch{settings.sound=false;}
 }
 function scoreMarkup(){const s=C.roundStats(state);return [['击杀',s.kills],['阵亡',s.deaths],['头部命中',s.headshots],['命中率',s.accuracy+'%'],['剩余时间',Math.ceil(state.time)+' 秒'],['行动积分',s.score]].map(([name,n])=>`<div><strong>${n}</strong><small>${name}</small></div>`).join('');}
 function openMenu(name){paused=true;menu=name;keys=Object.create(null);shooting=false;aiming=false;look=null;document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!==name);if(document.pointerLockElement)document.exitPointerLock();
  if(name==='scoreboard')$('score-stats').innerHTML=scoreMarkup();
 }
 async function lock(){if(isTouch||pointerFallback)return;try{await canvas.requestPointerLock();}catch{pointerFallback=true;shooting=false;$('touch-controls').style.display='block';toast('拖动画面观察；屏幕按钮控制开火与瞄准');}}
 function resume(){if(!playing)return;paused=false;menu=null;document.querySelectorAll('.screen').forEach(s=>s.hidden=true);keys=Object.create(null);shooting=false;lock();}
 function start(d=difficulty){difficulty=d;state=C.createState(d,Math.floor(Math.random()*4294967296));playing=true;paused=false;menu=null;resultSaved=false;feed=[];hitTimer=0;killTimer=0;renderer.effects=[];document.querySelectorAll('.screen').forEach(s=>s.hidden=true);$('hud').hidden=false;$('killfeed').innerHTML='';$('respawn-overlay').hidden=true;updateHud();drawMap();lock();audio('switch');toast('行动开始：4 分钟内完成 15 次击杀');}
 function returnMenu(){playing=false;paused=true;menu='welcome';shooting=false;aiming=false;keys=Object.create(null);renderer.effects=[];renderer.flash=0;$('hud').hidden=true;document.querySelectorAll('.screen').forEach(s=>s.hidden=s.id!=='welcome');if(document.pointerLockElement)document.exitPointerLock();state=C.createState(difficulty);updateBest();}
 function finish(){if(resultSaved)return;resultSaved=true;const stats=C.roundStats(state),newBest=!best||stats.score>best.score;
  let saved=true;if(newBest){best=stats;saved=storagePut(BEST,JSON.stringify(stats));}
  $('result-overline').textContent=state.status==='victory'?'目标达成 / 演练结束':'时间到 / 演练结束';$('result-title').textContent=state.status==='victory'?'行动完成。':'再试一次。';$('result-description').textContent=state.status==='victory'?'十五个目标全部清除。保持观察，继续挑战更快的节奏。':`本局清除了 ${state.kills} 个目标。下一次，试着多利用掩体与瞄准。`;
  $('result-stats').innerHTML=scoreMarkup();$('storage-status').textContent=!saved?'浏览器存储不可用，最佳战绩仅保留到关闭页面。':newBest?'已记录新的最高分。':'最高分 '+best.score+'，保存在此浏览器。';openMenu('result');updateBest();
 }
 function doFire(){if(paused||!playing)return;const result=C.fire(state,aiming,Math.hypot(state.player.vx,state.player.vz)>1);if(result.empty&&state.ammo[state.weapon].reserve>0)C.reload(state);}
 function events(){for(const e of state.events.splice(0)){
  renderer.event(e);
  if(e.type==='shot')audio(e.weapon);if(e.type==='enemy-shot')audio('enemy');if(e.type==='empty')audio('empty');if(e.type==='reload'||e.type==='reloaded'||e.type==='switch')audio(e.type);
  if(e.type==='hit'){hitTimer=.16;$('hit-marker').style.color=e.headshot?'#eaca88':'#fff';audio('hit');}
  if(e.type==='kill'){killTimer=1.5;$('kill-confirm').textContent=e.headshot?'头部命中 +150':'目标清除 +100';audio('kill');feed.unshift({text:`<b>你</b>　${e.headshot?'头部命中':'AR-9 / P-12'}　目标 ${e.id+1}`,life:6});feed=feed.slice(0,4);}
  if(e.type==='damage'){$('damage-flash').style.opacity='.9';setTimeout(()=>$('damage-flash').style.opacity='0',160);}
  if(e.type==='death'){feed.unshift({text:'<b>敌方</b>　击倒　你',life:6});shooting=false;aiming=false;}
  if(e.type==='respawn')toast('已回到战场：弹药与护甲恢复');if(e.type==='explosion')audio('explosion');if(e.type==='round-end')finish();
 }}
 function updateHud(){const p=state.player,a=state.ammo[state.weapon],w=C.WEAPONS[state.weapon];$('health').textContent=Math.ceil(p.health);$('armor').textContent=Math.ceil(p.armor);$('health-bar').style.width=p.health+'%';$('armor-bar').style.width=p.armor/75*100+'%';$('health-bar').style.background=p.health<30?'#db8a78':'#edf2dd';$('mag').textContent=a.mag;$('reserve').textContent=a.reserve;$('weapon-name').textContent=w.name;$('grenade-count').textContent=state.grenadeStock;$('score').innerHTML=state.kills+' <small>/ '+state.goal+'</small>';
  const t=Math.ceil(state.time);$('timer').textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');$('timer').style.color=t<30?'#e3ac85':'#f7f4e6';$('difficulty-text').textContent=C.DIFFICULTY[state.difficulty].name;
  $('reload-text').textContent=state.reloading>0?'换弹中… '+state.reloading.toFixed(1)+' 秒':a.mag===0?'弹匣已空 · 按 R 换弹':'R 换弹 · 右键 瞄准';$('reload-progress').style.display=state.reloading>0?'block':'none';$('reload-progress').firstElementChild.style.width=(1-state.reloading/w.reload)*100+'%';
  document.querySelectorAll('[data-weapon]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.weapon===state.weapon)));$('respawn-overlay').hidden=state.respawning<=0;$('respawn-timer').textContent=Math.ceil(state.respawning);$('touch-aim').setAttribute('aria-pressed',String(aiming));
 }
 function drawMap(){const ctx=$('minimap').getContext('2d'),m=state.map,sx=160/m.width,sz=140/m.depth;ctx.fillStyle='#293b3e';ctx.fillRect(0,0,160,140);for(const o of m.colliders){ctx.fillStyle=o.kind==='container'?'#61736e':o.kind==='warehouse'?'#4c6060':o.kind==='crate'?'#7b785b':'#788780';ctx.fillRect(o.min.x*sx,o.min.z*sz,(o.max.x-o.min.x)*sx,(o.max.z-o.min.z)*sz);}
  const p=state.player;for(const b of state.bots)if(b.health>0&&C.visible(m,{x:p.x,y:p.y+1.58,z:p.z},{x:b.x,y:b.y+1.5,z:b.z})){ctx.fillStyle='#d99770';ctx.beginPath();ctx.arc(b.x*sx,b.z*sz,2.2,0,Math.PI*2);ctx.fill();}
  ctx.save();ctx.translate(p.x*sx,p.z*sz);ctx.rotate(p.yaw);ctx.fillStyle='#f1dfae';ctx.beginPath();ctx.moveTo(0,-5);ctx.lineTo(-3,3);ctx.lineTo(0,1.5);ctx.lineTo(3,3);ctx.closePath();ctx.fill();ctx.restore();
 }
 function frame(now){const dt=Math.min(.05,(now-last)/1000||.016);last=now;
  if(playing&&!paused){const input={forward:keys.KeyW||keys.ArrowUp,back:keys.KeyS||keys.ArrowDown,left:keys.KeyA||keys.ArrowLeft,right:keys.KeyD||keys.ArrowRight,jump:keys.Space,sprint:keys.ShiftLeft||keys.ShiftRight,aim:aiming};C.step(state,input,dt);if(shooting&&C.WEAPONS[state.weapon].automatic)doFire();events();hudClock+=dt;mapClock+=dt;footClock+=dt;if(Math.hypot(state.player.vx,state.player.vz)>1&&state.player.grounded&&state.respawning<=0&&footClock>(input.sprint?.3:.44)){audio('step');footClock=0;}
   if(hudClock>.08){updateHud();hudClock=0;}if(mapClock>.3){drawMap();mapClock=0;}
   for(const row of feed)row.life-=dt;feed=feed.filter(row=>row.life>0);$('killfeed').innerHTML=feed.map(row=>`<div class="feed-row">${row.text}</div>`).join('');
  }
  hitTimer=Math.max(0,hitTimer-dt);killTimer=Math.max(0,killTimer-dt);$('hit-marker').style.opacity=hitTimer>0?'1':'0';$('kill-confirm').style.opacity=killTimer>0?'1':'0';$('reticle').classList.toggle('aim',aiming);$('reticle').style.setProperty('--gap',(5+state.player.recoil*90+(Math.hypot(state.player.vx,state.player.vz)>1?3:0))+'px');renderer.render(state,paused?0:dt,{...settings,aim:aiming,showcase:!playing});requestAnimationFrame(frame);
 }
 try{renderer=new root.StrikeRenderer.Renderer(canvas,state.map);}catch(e){$('welcome').hidden=true;$('unavailable').hidden=false;$('error-text').textContent=e.message;return;}
 updateBest();$('sensitivity').value=settings.sensitivity;$('sensitivity-value').textContent=settings.sensitivity.toFixed(1);$('fov').value=settings.fov;$('fov-value').textContent=settings.fov+'°';$('quality').value=settings.quality;$('sound').textContent='声音：'+(settings.sound?'开启':'关闭');$('sound').setAttribute('aria-pressed',String(settings.sound));requestAnimationFrame(frame);
 document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(other=>other.setAttribute('aria-pressed',String(b===other)));});
 $('start').onclick=()=>start();$('resume').onclick=resume;$('restart').onclick=()=>start(state.difficulty);$('again').onclick=()=>start(state.difficulty);$('return-menu').onclick=returnMenu;$('result-menu').onclick=returnMenu;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=resume);
 $('pause-button').onclick=()=>openMenu('pause');$('help-button').onclick=()=>openMenu('help');$('score-button').onclick=()=>openMenu('scoreboard');
 $('sensitivity').oninput=e=>{settings.sensitivity=+e.target.value;$('sensitivity-value').textContent=settings.sensitivity.toFixed(1);saveSettings();};$('fov').oninput=e=>{settings.fov=+e.target.value;$('fov-value').textContent=settings.fov+'°';saveSettings();};$('quality').onchange=e=>{settings.quality=e.target.value;saveSettings();};$('sound').onclick=()=>{settings.sound=!settings.sound;$('sound').textContent='声音：'+(settings.sound?'开启':'关闭');$('sound').setAttribute('aria-pressed',String(settings.sound));saveSettings();audio('switch');};
 document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>{if(!paused)C.switchWeapon(state,b.dataset.weapon);updateHud();});$('grenade-button').onclick=()=>{if(!paused)C.grenade(state);};
 canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('mousedown',e=>{if(paused||!playing||e.sourceCapabilities?.firesTouchEvents)return;if(!document.pointerLockElement){look={x:e.clientX,y:e.clientY};lock();return;}if(e.button===0){shooting=true;doFire();}if(e.button===2)aiming=true;});
 document.addEventListener('mouseup',e=>{if(e.button===0)shooting=false;if(e.button===2)aiming=false;look=null;});
 document.addEventListener('mousemove',e=>{if(paused||!playing)return;let dx=0,dy=0;if(document.pointerLockElement===canvas){dx=e.movementX;dy=e.movementY;}else if(look){dx=e.clientX-look.x;dy=e.clientY-look.y;look={x:e.clientX,y:e.clientY};}state.player.yaw+=dx*.0022*settings.sensitivity;state.player.pitch=C.clamp(state.player.pitch-dy*.0022*settings.sensitivity,-1.45,1.45);});
 document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement===canvas)look=null;else if(playing&&!paused&&menu===null&&!isTouch)openMenu('pause');});
 document.addEventListener('keydown',e=>{if(!playing||['INPUT','SELECT'].includes(e.target.tagName))return;const k=e.code;if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(k))e.preventDefault();if(k==='Escape'){if(paused&&['pause','help','scoreboard'].includes(menu))resume();else if(!paused)openMenu('pause');return;}if(k==='KeyH'&&!e.repeat){if(menu==='help')resume();else if(!paused)openMenu('help');return;}if(k==='Tab'&&!e.repeat){if(menu==='scoreboard')resume();else if(!paused)openMenu('scoreboard');return;}if(paused)return;keys[k]=true;if(k==='KeyR'&&!e.repeat)C.reload(state);if(k==='Digit1')C.switchWeapon(state,'rifle');if(k==='Digit2')C.switchWeapon(state,'pistol');if(k==='KeyG'&&!e.repeat)C.grenade(state);});
 document.addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('wheel',e=>{if(!paused&&playing){e.preventDefault();C.switchWeapon(state,state.weapon==='rifle'?'pistol':'rifle');}},{passive:false});
 window.addEventListener('blur',()=>{keys=Object.create(null);shooting=false;aiming=false;if(playing&&!paused)openMenu('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing&&!paused)openMenu('pause');});
 canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&playing&&!paused){look={x:e.clientX,y:e.clientY,id:e.pointerId};canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'&&look&&e.pointerId===look.id&&!paused){const scale=.0046*settings.sensitivity*(aiming?.6:1);state.player.yaw+=(e.clientX-look.x)*scale;state.player.pitch=C.clamp(state.player.pitch-(e.clientY-look.y)*scale,-1.45,1.45);look={x:e.clientX,y:e.clientY,id:e.pointerId};}});canvas.addEventListener('pointerup',()=>look=null);canvas.addEventListener('pointercancel',()=>look=null);
 const touchKeys={forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD',jump:'Space'};document.querySelectorAll('[data-touch]').forEach(b=>{const k=touchKeys[b.dataset.touch];b.addEventListener('pointerdown',e=>{e.preventDefault();if(paused)return;keys[k]=true;b.setPointerCapture(e.pointerId);});b.addEventListener('pointerup',()=>keys[k]=false);b.addEventListener('pointercancel',()=>keys[k]=false);});
 $('touch-fire').addEventListener('pointerdown',e=>{e.preventDefault();if(paused)return;shooting=true;doFire();$('touch-fire').setPointerCapture(e.pointerId);});$('touch-fire').addEventListener('pointerup',()=>shooting=false);$('touch-fire').addEventListener('pointercancel',()=>shooting=false);$('touch-aim').onclick=()=>{if(!paused){aiming=!aiming;updateHud();}};$('touch-reload').onclick=()=>{if(!paused)C.reload(state);};
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(playing)openMenu('pause');toast('图形环境已重置，请刷新页面重新进入战场');});
 root.StrikeArena=Object.freeze({game:Object.freeze({get state(){return Object.freeze({difficulty:state.difficulty,player:Object.freeze({...state.player}),weapon:state.weapon,ammo:Object.freeze({rifle:Object.freeze({...state.ammo.rifle}),pistol:Object.freeze({...state.ammo.pistol})}),kills:state.kills,deaths:state.deaths,headshots:state.headshots,time:state.time,status:state.status,reloading:state.reloading,respawning:state.respawning,shots:state.shots,hits:state.hits,bots:Object.freeze(state.bots.map(b=>Object.freeze({x:b.x,y:b.y,z:b.z,health:b.health,state:b.state})))});},get running(){return playing&&!paused;},get menu(){return menu;},get vertexCount(){return renderer.staticCount;}})});
})(typeof globalThis==='object'?globalThis:this);
