(function(){
  'use strict';
  const E=window.MetroEngine,$=id=>document.getElementById(id),KEY='windplay.metro-rush.profile.v1';
  let profile=E.profile(),storageOK=true;try{profile=E.restoreProfile(localStorage.getItem(KEY))||profile;}catch{storageOK=false;}
  const preferReduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(preferReduced)profile.settings.motion=false;
  let s=E.create('metro-01'),renderer,last=0,lastUI=0,countTime=0,pausedStatus='running',modalStatus='ready',resultHandled=false,toastTime=0,flashTime=0,audio=null,lastTap=0,swipe=null;
  let processedEvents=new WeakSet();
  try{renderer=new window.MetroRenderer.Renderer($('scene'));}catch(error){$('error').hidden=false;$('error-message').textContent=error.message;return;}
  Object.defineProperty(E,'game',{get:()=>JSON.parse(JSON.stringify(s))});Object.defineProperty(E,'savedProfile',{get:()=>JSON.parse(JSON.stringify(profile))});
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(profile));storageOK=true;}catch{storageOK=false;}$('storage-note').textContent=storageOK?'成绩、钱包和设置已在本机保存。':'当前浏览器不允许存储；成绩和服装仅在本次页面保留。';}
  function tone(freq=480,length=.08,type='triangle',gain=.07){if(!profile.settings.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+length);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+length);}catch{}}
  function notify(text){if(!text)return;$('toast').textContent=text;$('toast').classList.add('visible');toastTime=performance.now()+3000;}
  function flash(crash=false){if(!profile.settings.motion)return;$('flash').classList.toggle('crash',crash);$('flash').style.opacity=crash?'.38':'.12';flashTime=performance.now()+65;}
  function settingsUI(){document.body.classList.toggle('reduced-motion',!profile.settings.motion);$('audio').setAttribute('aria-pressed',profile.settings.sound);$('audio').textContent=profile.settings.sound?'♫':'♪';$('audio').setAttribute('aria-label',profile.settings.sound?'关闭音效':'开启音效');$('setting-sound').checked=profile.settings.sound;$('setting-motion').checked=profile.settings.motion;$('setting-quality').value=profile.settings.quality;}
  function homeUI(){$('start-best').textContent=profile.best.toLocaleString();$('wallet').textContent=profile.wallet.toLocaleString();$('best').textContent=profile.best.toLocaleString();settingsUI();}
  function start(){s=E.create(`metro-${profile.runs+1}`);s.status='countdown';countTime=0;processedEvents=new WeakSet();resultHandled=false;renderer.reset();$('start-screen').hidden=true;$('results').hidden=true;$('pause-screen').hidden=true;$('hud').hidden=false;$('touch-controls').hidden=false;$('countdown').hidden=false;$('countdown').textContent='3';$('hint').hidden=false;document.body.classList.add('running');tone(370,.2);update(true);}
  $('start').onclick=start;$('retry').onclick=start;
  function menu(){s=E.create('metro-01');renderer.reset();$('start-screen').hidden=false;$('results').hidden=true;$('pause-screen').hidden=true;$('hud').hidden=true;$('hint').hidden=true;$('touch-controls').hidden=true;$('countdown').hidden=true;document.body.classList.remove('running');homeUI();}
  $('menu').onclick=menu;
  function pause(){if(!['running','countdown'].includes(s.status))return;pausedStatus=s.status;s.status='paused';$('pause-screen').hidden=false;}
  function resume(){if(s.status!=='paused'||['help-screen','settings-screen','closet'].some(id=>!$(id).hidden))return;s.status=pausedStatus;$('pause-screen').hidden=true;}
  $('pause').onclick=()=>s.status==='paused'?resume():pause();$('resume').onclick=resume;
  function finish(){if(resultHandled)return;resultHandled=true;const oldBest=profile.best,reward=s.coins+s.missions.filter(m=>m.done).length*20;profile=E.finish(profile,s);persist();homeUI();$('results').hidden=false;$('pause-screen').hidden=true;$('hud').hidden=true;$('touch-controls').hidden=true;$('hint').hidden=true;$('countdown').hidden=true;$('result-kicker').textContent=s.score>oldBest?'新的个人纪录！':'这段路，跑得漂亮。';$('result-score').textContent=s.score.toLocaleString();$('result-distance').textContent=Math.floor(s.distance);$('result-coins').textContent=s.coins;$('result-missions').textContent=s.missions.filter(m=>m.done).length;$('result-cause').textContent=s.death&&s.death.type==='quit'?'你主动结束了旅程，金币和挑战奖励已结算。':({train:'撞上列车。试着从银色坡道登上车顶。',barrier:'碰到路障。提前跳跃或换道，下一次会更好。',beam:'碰到横梁。下滑穿过，留意顶部的红色标记。'}[s.death&&s.death.type]||'继续挑战更远的街区。');$('result-challenges').innerHTML=s.missions.map(m=>`<div class="${m.done?'done':''}"><span>${m.done?'✓':'○'} ${m.title}</span><span>${m.done?'+500 分 / +20 金币':`${Math.min(Math.floor(s[m.key]),m.target)} / ${m.target}`}</span></div>`).join('');$('result-wallet').innerHTML=`本次入账 <b>+${reward} ●</b>　钱包 <b>${profile.wallet} ●</b>`;tone(s.score>oldBest?740:220,.3);}
  $('quit').onclick=()=>{s.status='dead';s.death={type:'quit'};finish();};
  function openModal(id){modalStatus=s.status;if(['running','countdown'].includes(s.status))s.status='paused';$(id).hidden=false;}
  function closeModal(id){$(id).hidden=true;if(['running','countdown'].includes(modalStatus))s.status=modalStatus;}
  for(const id of['help','start-help'])$(id).onclick=()=>openModal('help-screen');for(const id of['help-close','help-done'])$(id).onclick=()=>closeModal('help-screen');
  for(const id of['settings-open','pause-settings'])$(id).onclick=()=>{settingsUI();openModal('settings-screen');};
  function saveSettings(){profile.settings.sound=$('setting-sound').checked;profile.settings.motion=$('setting-motion').checked;profile.settings.quality=$('setting-quality').value;settingsUI();persist();closeModal('settings-screen');}
  $('settings-done').onclick=saveSettings;$('settings-close').onclick=saveSettings;
  $('audio').onclick=()=>{profile.settings.sound=!profile.settings.sound;settingsUI();persist();if(profile.settings.sound)tone();};
  function closetUI(){$('closet-wallet').textContent=profile.wallet;$('skins').innerHTML='';for(const skin of E.SKINS){const selected=profile.skin===skin.id,owned=profile.skins.includes(skin.id),card=document.createElement('div');card.className=`skin-card${selected?' selected':''}`;card.style.setProperty('--jacket',skin.jacket);card.style.setProperty('--pants',skin.pants);card.style.setProperty('--accent',skin.accent);card.innerHTML=`<div class="skin-avatar" aria-hidden="true"><i class="head"></i><i class="cap"></i><i class="body"></i><i class="legs"></i><i class="feet"></i></div><strong>${skin.name}</strong>`;const b=document.createElement('button');b.textContent=selected?'已穿戴':owned?'穿上':`${skin.price} ● 解锁`;b.disabled=selected||!owned&&profile.wallet<skin.price;b.onclick=()=>{if(E.unlock(profile,skin.id)){persist();homeUI();closetUI();tone(580,.16);}};card.appendChild(b);$('skins').appendChild(card);}}
  $('closet-open').onclick=()=>{closetUI();openModal('closet');};$('closet-close').onclick=()=>closeModal('closet');
  function action(type){if(s.status!=='running'||['help-screen','settings-screen','closet'].some(id=>!$(id).hidden))return;if(type==='left')E.move(s,-1);if(type==='right')E.move(s,1);if(type==='jump')E.jump(s);if(type==='slide')E.slide(s);if(type==='board')E.board(s);update(true);}
  $('board').onclick=()=>action('board');for(const name of['left','right','jump','slide'])$('touch-'+name).onclick=()=>action(name);
  document.addEventListener('keydown',event=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement)return;const k=event.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' '].includes(k))event.preventDefault();if(event.repeat)return;if(k==='escape'){for(const id of['help-screen','settings-screen','closet'])if(!$(id).hidden){if(id==='settings-screen')saveSettings();else closeModal(id);return;}if(s.status==='paused')resume();else pause();return;}if(k==='p'){s.status==='paused'?resume():pause();return;}if(k==='arrowleft'||k==='a')action('left');if(k==='arrowright'||k==='d')action('right');if(k==='arrowup'||k==='w'||k===' ')action('jump');if(k==='arrowdown'||k==='s')action('slide');if(k==='b')action('board');if(k==='enter'&&s.status==='ready')start();});
  const scene=$('scene');scene.addEventListener('pointerdown',event=>{if(s.status!=='running')return;swipe={x:event.clientX,y:event.clientY,time:performance.now(),id:event.pointerId};scene.setPointerCapture(event.pointerId);});scene.addEventListener('pointerup',event=>{if(!swipe||swipe.id!==event.pointerId)return;const dx=event.clientX-swipe.x,dy=event.clientY-swipe.y,now=performance.now();if(Math.max(Math.abs(dx),Math.abs(dy))>24){if(Math.abs(dx)>Math.abs(dy))action(dx>0?'right':'left');else action(dy>0?'slide':'jump');lastTap=0;}else if(now-lastTap<300){action('board');lastTap=0;}else{action('jump');lastTap=now;}swipe=null;});scene.addEventListener('pointercancel',()=>swipe=null);
  addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
  scene.addEventListener('webglcontextlost',event=>{event.preventDefault();pause();$('error').hidden=false;$('error-message').textContent='显卡连接暂时中断。刷新网页即可重新进入城市，已结算的成绩与服装会保留。';});
  function update(force=false){if(!force&&performance.now()-lastUI<90)return;lastUI=performance.now();$('score').textContent=s.score.toLocaleString();$('distance').textContent=Math.floor(s.distance).toLocaleString();$('coins').textContent=s.coins;$('boards').textContent=s.boards;$('board').disabled=s.boards===0||s.board>0||s.status!=='running';$('board').querySelector('small').textContent=s.board>0?`护盾 ${Math.ceil(s.board)} 秒`:'B / 双击';$('district').textContent=['晨光街区','中央车站','河岸新城'][Math.floor(s.distance/(E.SEGMENT*8))%3];
    $('powers').innerHTML=[['board','◇','悬浮护盾',12],['magnet','∩','磁力吸附',10],['boots','↑','弹跳鞋',12],['double','×','双倍积分',10]].filter(([k])=>s[k]>0).map(([k,icon,label,limit])=>`<div class="power"><b>${icon}</b><span>${label}</span><time>${Math.ceil(s[k])}s</time><i><span style="width:${Math.min(100,s[k]/limit*100)}%"></span></i></div>`).join('');
    $('challenge').innerHTML='<div class="challenge-title">本次挑战</div>'+s.missions.map(m=>`<div class="mission-row${m.done?' done':''}">${m.done?'✓ ':''}${m.title}<small>${m.done?'完成':`${Math.min(Math.floor(s[m.key]),m.target)}/${m.target}`}</small><i><b style="width:${Math.min(100,s[m.key]/m.target*100)}%"></b></i></div>`).join('');
  }
  function events(){for(const e of s.events){if(processedEvents.has(e))continue;processedEvents.add(e);if(e.type==='coin')tone(880+s.combo%5*90,.055,'sine',.035);if(e.type==='jump')tone(340,.09,'triangle',.025);if(e.type==='slide')tone(160,.08,'triangle',.025);if(['power','mission','board','shield'].includes(e.type)){notify(e.text);tone(e.type==='shield'?260:620,.15);flash(e.type==='shield');}if(e.type==='crash'){tone(110,.27,'sawtooth',.045);flash(true);}}}
  function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(s.status==='countdown'){const prev=Math.ceil(3-countTime);countTime+=dt;const next=Math.ceil(3-countTime);if(prev!==next&&next>0){$('countdown').textContent=next;tone(370+next*70,.14);}if(countTime>=3){s.status='running';$('countdown').hidden=true;notify('追着金币跑，第一处路障在前方。');tone(780,.18);}}if(s.status==='running'){E.tick(s,dt);events();if(s.distance>160)$('hint').hidden=true;if(s.status==='dead')finish();}renderer.render(s,profile,profile.settings.motion?now/1000:s.time,s.status==='ready');update();if(now>toastTime)$('toast').classList.remove('visible');if(now>flashTime)$('flash').style.opacity=0;requestAnimationFrame(frame);}
  homeUI();persist();requestAnimationFrame(frame);
})();
