const test=require('node:test');
const assert=require('node:assert/strict');
const E=require('../src/engine.js');
function run(seed='test'){const s=E.create(seed);s.status='running';return s;}
function advance(s,seconds){for(let i=0;i<Math.ceil(seconds/.02);i++)E.tick(s,.02);}
function course(objects){const s=run();s.segments=[{index:0,start:0,district:0,objects}];s.collected=[];return s;}

test('seeded segments reproduce geometry and obstacle decisions',()=>{assert.deepEqual(E.segment('abc',5),E.segment('abc',5));assert.notDeepEqual(E.segment('abc',5),E.segment('xyz',5));for(let i=0;i<100;i++){const seg=E.segment('test',i);assert.equal(seg.start,i*48);assert.ok(seg.objects.every(o=>o.lane>=-1&&o.lane<=1&&o.d>=seg.start&&o.d<seg.start+48));}});
test('generated rows retain at least one viable lane across seeds',()=>{for(let seed=0;seed<40;seed++)for(let i=0;i<60;i++){const seg=E.segment(seed,i);for(let d=seg.start;d<seg.start+48;d+=.5){const blocked=new Set(seg.objects.filter(o=>['train','barrier','beam'].includes(o.type)&&d>=o.d-.65&&d<=o.d+o.length+.65).map(o=>o.lane));assert.ok(blocked.size<=2,`all lanes blocked at ${seed}/${i}/${d}`);}}});
test('lane changes are smooth, bounded and inactive while paused',()=>{const s=run();assert.ok(E.move(s,1));assert.equal(s.lane,1);assert.equal(s.x,0);E.tick(s,.02);assert.ok(s.x>0&&s.x<3.2);assert.equal(E.move(s,1),false);s.status='paused';const before=s.distance;assert.equal(E.move(s,-1),false);E.tick(s,.05);assert.equal(s.distance,before);});
test('jump/slide/train collision heights correspond to visible obstacle types',()=>{const s=run(),o={type:'barrier',lane:0,d:0,length:2,height:1.05};assert.ok(E.obstacleHit(s,o));s.y=1.4;assert.equal(E.obstacleHit(s,o),false);o.type='beam';s.y=0;assert.ok(E.obstacleHit(s,o));s.slide=.8;assert.equal(E.obstacleHit(s,o),false);o.type='train';o.height=2.75;s.y=2.75;s.slide=0;assert.equal(E.obstacleHit(s,o),false);s.y=2.2;assert.ok(E.obstacleHit(s,o));s.invulnerable=1;assert.equal(E.obstacleHit(s,o),false);});
test('jump follows a ballistic arc and cannot double jump',()=>{const s=run();assert.ok(E.jump(s));advance(s,.18);assert.ok(s.y>1);assert.equal(E.jump(s),false);advance(s,.8);assert.equal(s.y,0);assert.equal(s.vy,0);assert.equal(s.jumps,1);assert.ok(E.jump(s));});
test('ramp raises runner onto a train roof without a crash',()=>{const s=course([{id:'r',type:'ramp',lane:0,d:1,length:12,height:2.75},{id:'t',type:'train',lane:0,d:13,length:26,height:2.75}]);advance(s,1.2);assert.equal(s.status,'running');assert.equal(s.y,2.75);assert.equal(s.ground,2.75);assert.ok(E.move(s,1));advance(s,.7);assert.equal(s.status,'running');assert.equal(s.ground,0);assert.ok(s.y<2.75);});
test('board consumes a charge, absorbs one hit, and normal collisions end runs',()=>{const s=course([{id:'bar',type:'barrier',lane:0,d:1,length:1.5,height:1.05}]);assert.ok(E.board(s));assert.equal(s.boards,1);advance(s,.2);assert.equal(s.status,'running');assert.equal(s.board,0);assert.ok(s.invulnerable>0);const normal=course([{id:'bar',type:'barrier',lane:0,d:1,length:1.5,height:1.05}]);advance(normal,.1);assert.equal(normal.status,'dead');assert.equal(normal.death.type,'barrier');});
test('coins cannot be collected twice; magnet expands collection radius',()=>{const s=course([{id:'c',type:'coin',lane:1,d:1,length:1,height:1}]);advance(s,.2);assert.equal(s.coins,0);const magnet=course([{id:'c',type:'coin',lane:1,d:2,length:1,height:1}]);magnet.magnet=8;advance(magnet,.1);assert.equal(magnet.coins,1);advance(magnet,.2);assert.equal(magnet.coins,1);});
test('multiplier adds permanent points and score continues after expiration',()=>{const s=run();s.distance=100;s.points=100;s.double=.03;const scores=[];for(let i=0;i<6;i++){E.tick(s,.02);scores.push(s.score);}assert.ok(scores.at(-1)>scores[0]);assert.ok(s.points>s.distance);assert.ok(scores.every((v,i)=>!i||v>=scores[i-1]));});
test('successful pass counts only once; missions apply bonuses on completion frame',()=>{const s=course([{id:'bar',type:'barrier',lane:1,d:1,length:1.5,height:1.05}]);s.x=3.2;s.lane=1;s.y=1.5;s.vy=0;s.distance=3.55;for(let i=0;i<5;i++)E.tick(s,.01);assert.equal(s.nearMisses,1);const m=run();m.coins=30;E.tick(m,.01);assert.ok(m.missions.find(x=>x.key==='coins').done);assert.ok(m.score>=860);});
test('streaming keeps segment and collectible memory bounded over long runs',()=>{const s=run();for(let i=0;i<200;i++){s.distance=i*48;s.collected.push('expired-id');E.ensure(s);assert.ok(s.segments.length<=9);assert.ok(!s.collected.includes('expired-id'));assert.ok(s.segments.at(-1).start>=s.distance+240);}assert.ok(s.segments[0].start>9000);});
test('profile wallet, cosmetics and validation round trip safely',()=>{const p=E.profile(),s=run();s.coins=50;s.score=400;s.distance=150;s.missions[0].done=true;const q=E.finish(p,s);assert.equal(p.wallet,0);assert.equal(q.wallet,70);assert.equal(q.best,400);assert.equal(q.runs,1);assert.equal(E.unlock(q,'sunset'),false);q.wallet=200;assert.ok(E.unlock(q,'sunset'));assert.equal(q.wallet,50);assert.equal(q.skin,'sunset');assert.ok(E.unlock(q,'courier'));assert.equal(q.wallet,50);assert.deepEqual(E.restoreProfile(JSON.stringify(q)),q);for(const mutate of[x=>x.wallet=-1,x=>x.skins=['unknown'],x=>x.skin='midnight',x=>x.settings.quality='bad',x=>x.best=null]){const b=E.profile();mutate(b);assert.equal(E.restoreProfile(JSON.stringify(b)),null);}assert.equal(E.restoreProfile('{bad}'),null);});
