(function(){
'use strict';
const E=window.MarioEngine,L=window.MarioLevels,canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),byId=id=>document.getElementById(id);
let state=E.create(),running=false,acc=0,last=0,audio=null,sound=false;
const keys=new Set(),touch=new Map(),edge={jumpPressed:false,firePressed:false},done=new Set();
const SAVE='windplay:mario:save:v1',DONE='windplay:mario:completed:v1';
let saved=null;try{saved=E.restore(localStorage.getItem(SAVE));const a=JSON.parse(localStorage.getItem(DONE)||'[]');if(Array.isArray(a))a.filter(x=>Number.isInteger(x)&&x>=0&&x<32).forEach(x=>done.add(x));}catch{}
byId('continue').hidden=!saved;
for(let world=1;world<=8;world++){
 const row=document.createElement('div');row.className='world-row';const label=document.createElement('span');label.textContent='世界 '+world;row.append(label);
 for(let stage=1;stage<=4;stage++){const i=(world-1)*4+stage-1,b=document.createElement('button');b.type='button';b.className='level-button';b.dataset.index=i;b.textContent=L.levels[i].id;b.title=L.levels[i].name;b.setAttribute('aria-label','游玩 '+L.levels[i].id+' '+L.levels[i].name);b.onclick=()=>{state=E.create(i);document.querySelector('.console').scrollIntoView({block:'start',behavior:'instant'});start();};row.append(b);}byId('levels').append(row);
}
function selection(){byId('stage-name').textContent='WORLD '+state.level.id+' · '+state.level.name;document.querySelectorAll('.level-button').forEach(b=>{const i=Number(b.dataset.index);b.classList.toggle('current',i===state.index);b.classList.toggle('completed',done.has(i));b.setAttribute('aria-pressed',String(i===state.index));});byId('progress').textContent=done.size+' / 32 已通关';}
function save(){try{localStorage.setItem(SAVE,E.serialize(state));localStorage.setItem(DONE,JSON.stringify([...done]));saved=E.restore(E.serialize(state));}catch{byId('message').textContent='浏览器未允许存档，当前冒险仍可继续。';}}
function beep(name){if(!sound||!audio)return;const notes={jump:[330,660,.1],coin:[988,1319,.12],bump:[150,220,.08],break:[110,50,.1],power:[523,1047,.22],stomp:[150,65,.08],fire:[240,80,.08],hurt:[220,80,.2],death:[392,130,.45],clear:[523,1047,.55],life:[660,1320,.35],pipe:[250,100,.2],route:[600,900,.12],wrongroute:[160,90,.25]};const [a,b,t]=notes[name]||notes.coin,o=audio.createOscillator(),gain=audio.createGain();o.type='square';o.frequency.setValueAtTime(a,audio.currentTime);o.frequency.exponentialRampToValueAtTime(b,audio.currentTime+t);gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+t);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+t);}
function clearInput(){keys.clear();touch.clear();edge.jumpPressed=edge.firePressed=false;document.querySelectorAll('[data-input]').forEach(b=>b.classList.remove('held'));}
function start(){running=true;state.status='playing';byId('overlay').hidden=true;byId('pause').disabled=false;byId('pause').textContent='暂停';byId('message').textContent=state.level.theme==='water'?'反复按跳跃游泳，避开鱼和乌贼。':state.level.theme==='castle'?'避开火棒，越过库巴，在尽头触及斧头。':'向右出发。长按跳跃跳得更高，踩住敌人可以弹起。';clearInput();selection();save();canvas.focus({preventScroll:true});if(sound)audio?.resume();}
function overlay(title,note,action,label){running=false;clearInput();byId('overlay-title').textContent=title;byId('overlay-note').textContent=note;byId('primary').textContent=label;byId('primary').onclick=action;byId('continue').hidden=true;byId('overlay').hidden=false;byId('pause').disabled=true;byId('primary').focus({preventScroll:true});}
function pause(){if(!running){if(state.status==='paused'){state.status='playing';start();}return;}state.status='paused';save();overlay('暂停一下','世界 '+state.level.id+' · 冒险会在这里等你。',()=>{state.status='playing';start();},'继续游戏');byId('pause').disabled=false;byId('pause').textContent='继续';}
byId('primary').onclick=()=>start();byId('continue').onclick=()=>{if(saved)state=saved;start();};byId('pause').onclick=pause;byId('restart').onclick=()=>{state=E.create(state.index);start();};
byId('sound').onclick=async()=>{try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();sound=!sound;byId('sound').textContent='声音：'+(sound?'开':'关');byId('sound').setAttribute('aria-pressed',String(sound));if(sound)beep('coin');}catch{byId('message').textContent='此浏览器无法开启音效，可继续静音游玩。';}};
byId('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.console').requestFullscreen();}catch{byId('message').textContent='此浏览器暂不支持全屏，请横屏游玩。';}};
const jumpKeys=['Space','KeyZ','KeyW','ArrowUp'],runKeys=['ShiftLeft','ShiftRight','KeyX'];
function jumpHeld(){return jumpKeys.some(k=>keys.has(k))||[...touch.values()].includes('jump');}
function inputs(){const held=x=>[...touch.values()].includes(x);return {left:keys.has('ArrowLeft')||keys.has('KeyA')||held('left'),right:keys.has('ArrowRight')||keys.has('KeyD')||held('right'),down:keys.has('ArrowDown')||keys.has('KeyS')||held('down'),jump:jumpHeld(),run:runKeys.some(k=>keys.has(k))||held('run'),...edge};}
window.addEventListener('keydown',e=>{if(e.target.closest?.('button,a,input,select,textarea,[contenteditable]'))return;if(['KeyP','Escape'].includes(e.code)&&!e.repeat){if(state.status==='playing'||state.status==='paused'){e.preventDefault();pause();}return;}if(!running)return;const control=['ArrowLeft','ArrowRight','ArrowDown','KeyA','KeyD','KeyS',...jumpKeys,...runKeys];if(!control.includes(e.code))return;e.preventDefault();if(!keys.has(e.code)&&jumpKeys.includes(e.code))edge.jumpPressed=true;if(!keys.has(e.code)&&e.code==='KeyX')edge.firePressed=true;keys.add(e.code);});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();if(running)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause();});
const touchPad=document.querySelector('.touch-controls');document.querySelector('.console').append(touchPad);
for(const button of document.querySelectorAll('[data-input]')){
 button.addEventListener('pointerdown',e=>{if(!running)return;e.preventDefault();button.setPointerCapture(e.pointerId);touch.set(e.pointerId,button.dataset.input);button.classList.add('held');if(button.dataset.input==='jump')edge.jumpPressed=true;if(button.dataset.input==='run')edge.firePressed=true;});
 const release=e=>{touch.delete(e.pointerId);button.classList.toggle('held',[...touch.values()].includes(button.dataset.input));};button.addEventListener('pointerup',release);button.addEventListener('pointercancel',release);button.addEventListener('lostpointercapture',release);
}
function result(){if(state.status==='clear'||state.status==='won'){done.add(state.index);save();selection();if(state.status==='won')overlay('冒险完成！','32 关的终点。公主获救，你的分数是 '+state.score+'。',()=>{state=E.create();start();},'再来一轮');else overlay('WORLD '+state.level.id+'\nCLEAR!','分数 '+state.score+' · 下一关 '+L.levels[state.index+1].id,()=>{state=E.next(state);start();},'下一关');}
 else if(['dead','gameover'].includes(state.status)){save();overlay(state.status==='dead'?'再跳一次。':'GAME OVER',state.status==='dead'?'还剩 '+state.lives+' 条生命。重试世界 '+state.level.id+'。':'世界 '+state.level.id+' · 从这一关重新出发。',()=>{state=E.retry(state);start();},'重试本关');}}
let autosave=0;
function frame(now){const delta=Math.min(.08,(now-(last||now))/1000);last=now;if(running){acc+=delta;while(acc>=E.STEP&&running){E.step(state,inputs());edge.jumpPressed=edge.firePressed=false;acc-=E.STEP;if(state.status!=='playing')result();}autosave+=delta;if(autosave>5){autosave=0;save();}for(const name of state.events){beep(name);if(name==='wrongroute')byId('message').textContent='路线不对，已返回路口。按画面指示选择高路或低路。';else if(name==='route')byId('message').textContent='路线正确，继续前进！';}state.events=[];}else acc=0;window.MarioRender.render(ctx,state);requestAnimationFrame(frame);}
selection();requestAnimationFrame(frame);
})();
